In [1]:
import pandas as pd

In [2]:
cta_df = pd.read_parquet('output/cta_ridership.parquet')

In [3]:
cta_df.head(10)

  station_id              stationname                     date daytype rides
0      40350              UIC-Halsted  2001-01-01T00:00:00.000       U   273
1      41130           Halsted-Orange  2001-01-01T00:00:00.000       U   306
2      40760                Granville  2001-01-01T00:00:00.000       U  1059
3      40070         Jackson/Dearborn  2001-01-01T00:00:00.000       U   649
4      40090              Damen-Brown  2001-01-01T00:00:00.000       U   411
5      40590          Damen/Milwaukee  2001-01-01T00:00:00.000       U   870
6      40720  East 63rd-Cottage Grove  2001-01-01T00:00:00.000       U   391
7      41260              Austin-Lake  2001-01-01T00:00:00.000       U   399
8      40230               Cumberland  2001-01-01T00:00:00.000       U   788
9      41120       35-Bronzeville-IIT  2001-01-01T00:00:00.000       U   448

# Date features

## Day of week

In [6]:
cta_df['date'] = pd.to_datetime(cta_df['date'])
cta_df['day_of_week_num'] = cta_df['date'].dt.weekday
cta_df['day_of_week_name'] = cta_df['date'].dt.day_name()

cta_df.head(10)

,station_id,stationname,date,daytype,rides,day_of_week_num,day_of_week_name
0,40350,UIC-Halsted,2001-01-01,U,273,0,Monday
1,41130,Halsted-Orange,2001-01-01,U,306,0,Monday
2,40760,Granville,2001-01-01,U,1059,0,Monday
3,40070,Jackson/Dearborn,2001-01-01,U,649,0,Monday
4,40090,Damen-Brown,2001-01-01,U,411,0,Monday
5,40590,Damen/Milwaukee,2001-01-01,U,870,0,Monday
6,40720,East 63rd-Cottage Grove,2001-01-01,U,391,0,Monday
7,41260,Austin-Lake,2001-01-01,U,399,0,Monday
8,40230,Cumberland,2001-01-01,U,788,0,Monday
9,41120,35-Bronzeville-IIT,2001-01-01,U,448,0,Monday

# Save the data

In [7]:
cta_df.to_parquet('output/cta_ridership_with_features.parquet', engine='fastparquet', index=False)